Repository Already-12-O-clock/ABCDmoviE, pull requests merged in 2022-11, with the labels that each got.

#2 [feat] README.md skills 제안
  README.md
Labels: issue

#5 style: 공통 스타일 설정(reset.css)
  .gitignore
  index.html
  src/pages/mainPage.html
  src/styles/reset.css
  src/styles/style.css
Labels: style

#7 Minutes/22.11.09
  minutes/11.09/Readme.md
Labels: documentation

#9 docs: 11월 07일 회의록
  minutes/11.07/Readme.md
Labels: documentation

#11 docs: README.md 수정
  README.md
Labels: documentation

#12 feat: KMDB, KOBIS service 키 관리
  .gitignore
Labels: api

#10 docs: git commit 컨벤션
  minutes/conventions/git_commit.md
Labels: documentation

#13 docs: 11월 14일 회의록
  minutes/11.14/Readme.md
Labels: documentation

#17 style: logo 이미지 수정 및 생성
  src/img/logo.png
  src/img/logo_black.png
Labels: style

#20 docs: 11월 15일 회의록
  minutes/11.15/Readme.md
Labels: documentation

#26 style: index.html과 mainPage.html에 font-awesome 적용
  index.html
  src/pages/mainPage.html
Labels: HTML, style

#24 style: 빠른 예매 페이지 - 레이아웃 구현
  src/pages/selectTheaterPage.html
  src/styles/components/aside.css
  src/styles/components/main.css
Labels: HTML, CSS, style

#25 fix: 메인 페이지 로그인 버튼 스타일 속성 수정
  src/styles/components/header.css
Labels: style, fix

#29 fix: mainPage.html 로그인 a 요소 클래스명 추가
  src/pages/mainPage.html
Labels: HTML, fix

#30 fix: selectTheaterPage.html 로그인 a 요소 클래스명 추가
  src/pages/selectTheaterPage.html
Labels: HTML, fix

#31 style: ticketingPage페이지 레이아웃 수정
  src/pages/ticketingPage.html
  src/styles/components/aside.css
  src/styles/components/main.css
  src/styles/ticketingPage.css
Labels: HTML, CSS, style, fix

#32 setting: npm 개발 환경 설정- Package.json, Package-lock.json, .env, .gitignore, requestAPI.js
  .gitignore
  package-lock.json
  package.json
  requestAPI.js
Labels: api

#34 setting: package.json type 설정
  package.json
Labels: api

#28 style: index 페이지 마크업과 스타일링
  index.html
  src/styles/index.css
Labels: HTML, CSS, style

#38 docs: 11월 22일 회의록
  minutes/11.22/Readme.md
  src/pages/loginPage.html
  src/styles/components/login.css
Labels: documentation

#39 setting: package.json_and_package-lock.json/find-config 모듈 추가
  package-lock.json
  package.json
Labels: npm

#40 feat: requestAPI.js/createDB 함수 생성
  requestAPI.js
Labels: api

#37 style: mainPage 최신영화목록 제공, detailPage 영화상세정보 제공 html 및 css 작성, 이미지 파일 추가
  src/img/cover.png
  src/img/star.png
  src/pages/detailPage.html
  src/pages/mainPage.html
  src/styles/components/main.css
  src/styles/detailPage.css
Labels: HTML, CSS

#44 feat: DB 폴더 구조 변경
  db/DB_desc.md
  db/kmdb_db/one_data_kmdb.json
  db/kmdb_db/search_data_kmdb.json
  db/kobis_db/daily_boxoffice_data_kobis.json
  db/kobis_db/weekly_boxoffice_data_kobis.json
Labels: api

#41 feat: naver openAPI를 통한 데이터 요청 방법 및 간단한 바닐라JS SPA 페이지 구현
  .gitignore
  src/js/test.js
  src/pages/test.html
Labels: documentation, HTML, JavaScript, api

#36 style: ticketing페이지 상영관선택, 영화선택 파트 html 및 css 작성
  src/img/icon-Triangle-down.png
  src/img/icon-Triangle-up.png
  src/pages/ticketingPage.html
  src/styles/ticketingPage.css
Labels: HTML, CSS, style

#46 feat: db/box_office_db.json 생성
  .gitignore
  db/box_office_db.json
Labels: api
