Repository Already-12-O-clock/ABCDmoviE, pull requests merged in 2022-12, with the labels that each got.

#45 feat: 캐러셀 페이지 기능 구현
  index.html
  src/js/index.js
  src/js/test.js
  src/pages/test.html
  src/styles/index.css
Labels: HTML, CSS, JavaScript

#48 feat: 빠른 예매 페이지 슬라이드 구현
  src/js/ticketingPageOverall.js
  src/pages/ticketingPage.html
  src/styles/ticketingPage.css
Labels: HTML, CSS, JavaScript

#50 fix: fetchAPI 요청 URL 404에 따른 수정작업
  README.md
  src/js/index.js
Labels: api, fix

#49 docs: README.md 프로젝트에 사용된 기술 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#51 docs: PR 메시지 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#52 docs: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/before_feat.md
Labels: documentation

#57 docs: 커밋 메시지 타입 변경
  README.md
Labels: docs

#58 chore: index.js 불필요한 코드 주석 제거
  src/js/index.js
Labels: chore

#59 feat: box_office_db.json 데이터 요청 및 타이틀 정보 필터 함수 적용
  src/js/index.js
  src/js/main.js
  src/pages/mainPage.html
Labels: JavaScript, feat

#61 feat: box_office_db.json 데이터를 이용하여 요소 내 데이터 전달
  src/js/main.js
  src/pages/mainPage.html
Labels: HTML, JavaScript, api, feat

#63 fix: 이미지를 불러올 수 없는 경우 대체 이미지로 변경
  src/js/main.js
Labels: bug, JavaScript, fix

#65 fix: mainPage 디자인 개선
  src/js/main.js
  src/pages/mainPage.html
  src/styles/components/main.css
Labels: HTML, JavaScript, design, fix, CSS

#68 fix: header nav 메뉴 a요소 페이지 링크 연결 및 상영관 선택 article 이미지 url 설정
  src/pages/mainPage.html
  src/pages/ticketingPage.html
Labels: HTML, fix

#69 feat: 빠른 예매 페이지 내 상영관 선택 article 드롭다운 기능 구현
  src/js/theaterSelect.js
Labels: JavaScript, feat

#71 design: 빠른 예매 페이지 progress-list li요소 cursor:pointer 적용
  src/styles/ticketingPage.css
Labels: design, CSS

#73 design: 로그인 페이지 로그인 박스의 브라우저 내 위치 조정을 위해 margin 조정
  src/styles/components/login.css
Labels: design, CSS

#75 feat: progress 메뉴 버튼 디자인 및 활성화 기능 구현
  src/js/ticketingPageOverall.js
Labels: JavaScript, design, feat
