Repository Already-12-O-clock/ABCDmoviE, pull requests merged in 2023-01, with the labels that each got.

#77 feat: fetchAPI 데이터 요청 MovieData 클래스로 분리 및 정규표현식 메서드 추가
  src/js/getMovieData.js
Labels: JavaScript, feat

#79 feat: MovieData 클래스를 이용하여 데이터 요청하도록 변경
  src/js/index.js
Labels: JavaScript, feat

#81 chore: index.js filterTitleReg 정규표현식 오타 수정
  src/js/index.js
Labels: fix, chore

#83 feat: main.js에서 데이터 요청 MovieData 클래스 이용
  src/js/main.js
Labels: JavaScript, fix, feat

#86 fix: index.html, mainPage.html 문서 script type을 module로 변경
  index.html
  src/pages/mainPage.html
Labels: HTML, fix

#88 feat: 영화 선택 기능 구현
  src/js/movieSelect.js
  src/pages/ticketingPage.html
Labels: JavaScript, feat

#90 design: ticketingPage 영화선택 article 스타일 수정
  src/js/main.js
  src/styles/components/main.css
  src/styles/ticketingPage.css
Labels: JavaScript, design, fix, CSS

#93 chore: 불필요한 주석 코드 제거
  src/js/ticketingPageOverall.js
Labels: chore

#94 fix: 극장판 소드 아트 온라인과 같이 이미지를 불러올 수 없는 경우 대체 이미지로 적용
  src/js/main.js
Labels: JavaScript, design, fix

#95 docs: README 빠른 예매 페이지 > 영화 선택 미리보기 이미지 추가
  README.md
Labels: docs

#99 bug: index.js에서의 fetch 진행
  src/js/index.js
Labels: bug, fix
